#!/bin/bash
. $1
ansible-playbook remove_cleanup.yaml --extra-vars "variable=$2"
bastion_floating_ip=$(cat ./temp/bastionfloating)
openstack floating ip delete "$bastion_floating_ip"
haproxy_floating_ip=$(cat ./temp/haproxyfloating)
openstack floating ip delete "$haproxy_floating_ip"
rm -r ./temp
rm ./hosts
rm ./"$2"_SSHconfig
