---
- hosts: localhost
  tasks:
  - name: list the vm in a file with hostnames
    shell: openstack server list -f value >> ./temp/totalhosts && grep -nr "$2_network" ./temp/totalhosts > ./temp/requiredhosts && awk '{print $2}' ./temp/requiredhosts >> ./temp/namesofhost
  - name: create a hosts file
    shell: python3 ./hosts.py
  - name: create a config file
    shell: python3 ./config.py
  
