---
- hosts: localhost
  tasks:
  - name: Create server devhaproxy
    os_server:
      state: present
      name: "{{ lookup('file', './temp/haproxy') }}"
      image: Ubuntu 22.04.1 Jammy Jellyfish 230124
      flavor: "{{ lookup('file', './flavor') }}"
      auto_floating_ip: yes
      security_groups: "{{ lookup('file', './temp/securityname') }}"
      key_name: "{{ lookup('file', './temp/ansible_key') }}"
      nics:
        - net-id: "{{ lookup('file', './temp/testnetwork.id') }}"
          fixed_ip: 192.168.0.11
    register: devhaproxy
  - local_action: copy content={{ devhaproxy.openstack.public_v4 }} dest=./temp/haproxyfloating
  - name: Create server devhaproxy1
    os_server:
      state: present
      name: "{{ lookup('file', './temp/haproxy1') }}"
      image: Ubuntu 22.04.1 Jammy Jellyfish 230124
      flavor: "{{ lookup('file', './flavor') }}"
      auto_floating_ip: no
      security_groups: "{{ lookup('file', './temp/securityname') }}"
      key_name: "{{ lookup('file', './temp/ansible_key') }}"
      nics:
        - net-id: "{{ lookup('file', './temp/testnetwork.id') }}"
          fixed_ip: 192.168.0.12
