---
- hosts: localhost
  tasks:
  - name: delete server
    os_server:
      name: '{{ item }}'
      state: absent
    with_items: "{{ lookup('file', './temp/deletehostnames').splitlines() }}"
  - name: create servers if absent & check whether all required no of servers are present
    os_server:
      state: present
      name: "{{ item.0 }}"
      image: Ubuntu 22.04.1 Jammy Jellyfish 230124
      flavor: "{{ lookup('file', './flavor') }}"
      key_name: "{{ lookup('file', './temp/ansible_key') }}"
      auto_floating_ip: no
      security_groups: default
      nics:
        - net-id: "{{ lookup('file', './temp/testnetwork.id') }}"
          fixed_ip: "{{ item.1 }}"
    with_together: 
        - "{{ lookup('file', './temp/hostnames').splitlines() }}"
        - "{{lookup('file','./temp/fixedip').splitlines()}}"
