---
- hosts: localhost
  tasks: 
  - name: create servers 
    os_server:
      state: present
      name: "{{ item.0 }}"
      image: Ubuntu 22.04.1 Jammy Jellyfish 230124
      flavor: "{{ lookup('file', './flavor') }}"
      key_name: "{{ lookup('file', './temp/ansible_key') }}"
      auto_floating_ip: no
      security_groups: "{{ lookup('file', './temp/securityname') }}"
      nics:
        - net-id: "{{ lookup('file', './temp/testnetwork.id') }}"
          fixed_ip: "{{ item.1 }}"
    with_together: 
        - "{{ lookup('file', './temp/hostnames').splitlines() }}"
        - "{{lookup('file','./temp/fixedip').splitlines()}}"
