---
- hosts: webservers
  gather_facts: yes
- hosts: haproxy
  gather_facts: yes
  become: yes
  vars:
    haproxy_maxconns: 4096
    haproxy_backlog: 2
    haproxy_timeout_q: 400ms
    haproxy_timoutconnect: 5000ms
    haproxy_timeoutclient: 5000ms
    haproxy_timoutserver: 5000ms
    haproxy_http_timeout: 15s
    haproxy_balance: leastconn
    haproxy_frontend_port: 5000
  tasks:
  - name: Update cache
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 7200

  - name: Installing packages
    become: true
    apt:
      name: haproxy
      state: latest

  - name: Deploy HAProxy
    template:
      src: ./flask/haproxy.conf
      dest: "/etc/haproxy/haproxy.cfg"

  - name: restart Haproxy
    service:
      name: haproxy
      state: restarted

  - name: make sure snmp is installed
    apt: name=snmp state=latest

  - name: Installing the packages from Nginx
    become: true
    apt:
      name: nginx
      state: latest

  - name: copy nginx.conf file
    template:
     src: "./flask/nginx1.conf"
     dest: /etc/nginx/nginx.conf

  - name: restart  nginx
    service:
      name: nginx
      state: restarted

  - name: haproxy redumentary function test-1
    uri: url=http://localhost:5000/ return_content=yes
    register: html_body
  - debug: msg='{{ html_body.content }}'

  - name: haproxy redumentary function test-2
    uri: url=http://localhost:5000/ return_content=yes
    register: html_body
  - debug: msg='{{ html_body.content }}'

  - name: haproxy redumentary function test-3
    uri: url=http://localhost:5000/ return_content=yes
    register: html_body
  - debug: msg='{{ html_body.content }}'
  
  - name: haproxy redumentary function test-4
    uri: url=http://localhost:5000/ return_content=yes
    register: html_body
  - debug: msg='{{ html_body.content }}'
  
  - name: haproxy redumentary function test-5
    uri: url=http://localhost:5000/ return_content=yes
    register: html_body
  - debug: msg='{{ html_body.content }}'


  - name: checking snmpwalk -1
    shell: "snmpwalk -t 1 -r 1 -v2c -c public localhost:6000 iso.3.6.1.2.1.1.1.0"
    register: "output"
  - debug: var=output.stdout_lines

  - name: checking snmpwalk -2
    shell: "snmpwalk -t 1 -r 1 -v2c -c public localhost:6000 iso.3.6.1.2.1.1.1.0"
    register: "output"
  - debug: var=output.stdout_lines

  - name: checking snmp walk -3
    shell: "snmpwalk -t 1 -r 1 -v2c -c public localhost:6000 iso.3.6.1.2.1.1.1.0"
    register: "output"
  - debug: var=output.stdout_lines
  - name: checking snmpwalk -4
    shell: "snmpwalk -t 1 -r 1 -v2c -c public localhost:6000 iso.3.6.1.2.1.1.1.0"
    register: "output"
  - debug: var=output.stdout_lines
  - name: checking snmpwalk -5
    shell: "snmpwalk -t 1 -r 1 -v2c -c public localhost:6000 iso.3.6.1.2.1.1.1.0"
    register: "output"
  - debug: var=output.stdout_lines