---
- hosts: localhost
  gather_facts: false
  tasks: 
  - name: create servers 
    os_server:
      state: present
      name: "{{ item.0 }}"
      image: Ubuntu 22.04.1 Jammy Jellyfish 230124
      flavor: "{{ lookup('file', '../flavor') }}"
      key_name: "{{ variable }}_key"
      auto_floating_ip: no
      security_groups: "{{ variable }}_securitygroup"
      nics:
        - net-id: "{{ lookup('file', '../temp/testnetwork.id') }}"
          fixed_ip: "{{ item.1 }}"
    with_together: 
        - "{{ lookup('file', '../temp/hostnames').splitlines() }}"
        - "{{lookup('file','../temp/fixedip').splitlines()}}"
    async: 60
    poll: 0
