---
- hosts: webservers
  gather_facts: false
  become: yes
  tasks:
  - name: Updation of Cache
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 7200
      force: yes
  - name: install python3-venv
    pip:
      name: virtualenv
      state: latest

  - name: install wheel
    pip:
      name: wheel
      state: latest
      virtualenv: /home/ubuntu/project/venv

  - name: install flask in venv
    pip:
      name: flask
      state: latest
      virtualenv: /home/ubuntu/project/venv

  - name: install gunicorn
    pip:
      name: gunicorn
      state: latest
      virtualenv: /home/ubuntu/project/venv

  - name: copy flask app
    copy: src=../flask/flaskapp.py dest=/home/ubuntu/project/flaskapp.py
  - name: copy wsgi
    copy: src=../flask/wsgi.py dest=/home/ubuntu/project/wsgi.py
  - name: copy service
    copy: src=../flask/flask.service dest=/etc/systemd/system/flask.service
  - name: copy nginx
    copy: src=../flask/nginx.conf dest=/etc/nginx/conf.d/flask.conf
  - name: copy snmpd.conf file
    copy: src=../flask/snmpd.conf dest=/etc/snmp/snmpd.conf

  - name: restart snmpd
    service:
      name: snmpd
      state: restarted
    become: yes

  - name: restart nginx
    service:
      name: nginx
      state: restarted
  - name: systemd service start
    service:
      name: flask.service
      state: restarted
