---
- name: Install and configure Prometheus
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Update cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 7200

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present
        update_cache: yes
- hosts: Bastionhost
  gather_facts: false
  become: true
  tasks:
    - name: Configure Prometheus
      template:
        src: ../temp/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted
           

