---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: delete keypairs
    os_keypair:
      name: "{{ variable }}_key"
      state: absent
  - name: delete floating ip of bastion
    os_floating_ip:
      state: absent
      floating_ip_address: "{{ lookup('file', '../temp/bastionfloating') }}"
      network: ext-net
      server: "{{ variable }}_bastion"
    ignore_errors: yes
  - name: delete floating ip of haproxy
    os_floating_ip:
      state: absent
      floating_ip_address: "{{ lookup('file', '../temp/haproxyfloating') }}"
      server: "{{ variable }}_haproxy"
      network: ext-net
    ignore_errors: yes
  - name: delete all servers
    os_server:
      name: '{{ item }}'
      state: absent
    with_items: "{{ lookup('file', '../temp/pingreachable').splitlines() }}"
  - name: delete router
    os_router:
      name:  "{{ variable }}_router"
      state: absent
  - name: delete subnet
    os_subnet:
      name:  "{{ variable }}_subnet"
      cidr: 192.168.0.0/24
      state: absent
  - name: delete network
    os_network:
      name:  "{{ variable }}_network"
      state: absent
  - name: delete security group
    os_security_group:
      state: absent
      name: "{{ variable }}_securitygroup"
